server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lordtryndamere/fast-food-app
          basedir: target/config
          default-label: main